apiVersion : apps/v1
kind : Deployment
metadata :
  name : nginx-deployment
  labels:
    app : nginx
spec :
  replicas : 2
  selector : #which pods to manage
    matchLabels : 
      app: nginx
  template : #pods template
    metadata :
      labels:
        app: nginx
    spec:
        containers :
        - name : nginx
          image : nginx:1.14.1
          ports :
            - containerPort: 80

