apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port : 80
    targetPort: 8080
    nodePort: 30001
  selector :
    app : nginx